server.port=8080

spring.application.name=booking-app

spring.datasource.url=jdbc:h2:mem:member
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.INDENT_OUTPUT=true

logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.SQL=DEBUG

jwt.secret=5b8a5c4c8b8fdc3d7e5b9c1f8e9d4a7c5b8a5c4c8b8fdc3d7e5b9c1f8e9d4a7c
#2 minutes
jwt.access-token-expiration=120000
#15 minutes
#jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html